version: '3'

services:
  bitbucket:
    image: blacklabelops/bitbucket
    depends_on:
      - postgres_bitbucket
    networks:
      - bitbucketnet
    volumes:
      - bitbucketdata:/var/atlassian/bitbucket
    ports:
      - '80:7990'
    environment:
      - 'BITBUCKET_PROXY_NAME='
      - 'BITBUCKET_PROXY_PORT='
      - 'BITBUCKET_PROXY_SCHEME='
      - 'BITBUCKET_DELAYED_START='
      - 'DOCKER_WAIT_HOST=postgres_bitbucket'
      - 'DOCKER_WAIT_PORT=5432'
    labels:
      com.blacklabelops.description: "Atlassian Bitbucket"
      com.blacklabelops.service: "bitbucket"

  postgres_bitbucket:
    image: blacklabelops/postgres
    networks:
      - bitbucketnet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=bitbucketdb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=bitbucketdb'
      - 'POSTGRES_ENCODING=UTF8'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  bitbucketdata:
    external: false
  postgresqldata:
    external: false

networks:
  bitbucketnet:
    driver: bridge
